### ISSUE TITLE
Adding sponsor image

### ISSUE THREAD

**Issue by weaverbel** [resbaz/resbaz2017#26]
Hi @DamienIrving How do I add a sponsor logo? I uploaded qcif.png but it didn't display properly so I took it back out. Also where should images sit? I am sure it is in the wrong place.

**Comment by DamienIrving** [comment]
@weaverbel If you put your image in the `img/sponsors/` directory then you can update the header information in `brisbane.html` so that it refers to it. 

In other words, replace this:

```
sponsors:
 - name: 'Sponsor Number one'
   img: fake-sponsor.png
 - name: 'Sponsor Number Two'
   img: fake-sponsor.png
 - name: 'Sponsor Number Three'
   img: fake-sponsor.png
```

with

```
sponsors:
 - name: 'QCIF'
   img: qcif.png
```
